### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by daviddias**
We created a logo to help the clarify the difference between js-ipfs and js-ipfs-api. Would you like to add to your client library as well? You can see how it looks here: https://github.com/ipfs/js-ipfs-api

This design is from @akrych 🌟

### CODE REVIEW

**Comment by Fryie** [comment]
Thanks. Please be aware that I'm currently not maintaining this unfortunately. :(

**Comment by daviddias** [comment]
Thank you @Fryie! Could open an issue to look for other volunteers? Perhaps @kyledrake would like to jump in :)

**Comment by Fryie** [comment]
we have this already: https://github.com/Fryie/ipfs-ruby/issues/1

I also remember that there was some other person who was working on an alternative implementation for Ruby, unfortunately I don't remember who it was or what the name of the repo is. Maybe there is more progress there.

**Comment by Fryie** [comment]
found it: https://github.com/hjoest/ruby-ipfs-api

It seems to do more than this current gem and was last updated in February. Maybe you can have a look at it, if so, I can discontinue this gem and link to the other one instead.

**Pull request merged**
